### ISSUE TITLE
Hang on Uncharted Legacy of Thieves Collection

### ISSUE THREAD

**Issue by cripto135** [Recol/DLSS-Updater#6] opened 2024-08-31 18:30 UTC
Script seems to hang at "Checking if file is in use..." for Legacy of Thieves Collection on Steam
![image](https://github.com/user-attachments/assets/7ede95e8-acec-4717-9280-100eac2713f6)

**Comment by Recol** [comment] 2024-09-01 11:15
Unsure on the reason in particular, likely a bug to do with the await integration but tricky to tell, if you can rerun it 1/2 times to see if the same behaviour reproduces this will be helpful (in which case it's likely to do with this game in particular which I'll investigate further if so).

**Comment by Chubakabrah** [comment] 2024-09-01 18:01
Mine is also hanging, which never allows any .dlls to update.  Mine is hanging on Throne and Liberty Closed Beta Test.
![Untitled](https://github.com/user-attachments/assets/23134b3a-05d4-4462-b50b-7867475f3f8d)

**Comment by Recol** [comment] 2024-09-01 20:07
Hi both @Chubakabrah @cripto135 i have performed some changes to attempt to mitigate this behaviour, if you could report back if this occurs with version 2.0.1 this would be appreciated.

**Comment by Chubakabrah** [comment] 2024-09-01 20:27
@Recol Working great.  2.0.2 seems super fast as well.

**Comment by Recol** [comment] 2024-09-01 20:30
@Chubakabrah Greatly appreciated thanks for the feedback :)

**Comment by cripto135** [comment] 2024-09-02 04:03
> Hi both @Chubakabrah @cripto135 i have performed some changes to attempt to mitigate this behaviour, if you could report back if this occurs with version 2.0.1 this would be appreciated.

Retested on 2.0.5 and bug could not be reproduced
![image](https://github.com/user-attachments/assets/ab0226c7-0224-48db-be72-7e96cb90dcf5)
It did seem to have a bit of trouble but the script ran very quickly and I only noticed going back through
![image](https://github.com/user-attachments/assets/e1ccc43b-48ab-4a99-8380-52fbad67e9d5)

There were two oddities though, the Summary as shown has some duplicate entries and the game UBoat failed
![image](https://github.com/user-attachments/assets/721156b6-c583-461a-87ca-6a3db01e0737)

**Comment by Chubakabrah** [comment] 2024-09-02 08:27
@cripto135 I've noticed it will fail if the .dll is already the correct version.  Also I'm thinking the duplicate is because he's now including the frame generation .dll as well as dlss.

**Comment by Recol** [comment] 2024-09-02 14:47
> @cripto135 I've noticed it will fail if the .dll is already the correct version. Also I'm thinking the duplicate is because he's now including the frame generation .dll as well as dlss.

This is correct, as it's including FG/RR DLL's it will (duplicate) the output, I'll maybe try and tidy up the output to prevent this, closing this issue for now as it's resolved.

**Closed by Recol** 2024-09-02 14:47 UTC
Labels: bug, question
